### PR TITLE
Major refactor for 0.0.3

### PR DESCRIPTION
**Pull request by shai-almog**
Removed Snyk badge which isn't working.
Moved common code that was really backend state into the backend.
Created initial web interface
Implemented first CLI end to end

### CODE REVIEW

**Review by kiranborade — COMMENTED** [review]
[Do java]() 

> Rt

**Comment by kiranborade** [comment]
So later modling work at

**Comment by kiranborade** [comment]
#3

**Comment by shai-almog** [comment]
> So later modling work at

I don't follow?

**Pull request merged**
